services:
  php:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - '${APP_PORT:-80}:80'  # Map host port 80 to container port 80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - default
    depends_on:
      - php
    healthcheck:
      test:
        - CMD
        - curl
        - '-I'
        - 'http://tablerelations.test:${APP_PORT:-80}'
      retries: 3
      timeout: 5s

  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: unless-stopped
    ports:
      - '${DB_PORT:-3308}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 10s

networks:
  default:
    driver: bridge

volumes:
  mysql:
    driver: local
